### ISSUE TITLE
Msfs 2020 compatibiliy

### ISSUE THREAD

**Issue by ckosmowski** [mharj/jsimconnect#2]
Is it possible to make this compatible to msfs2020

**Comment by mharj** [comment]
This repo was just copied from http://lc0277.gratisim.fr/ and published with owners permission.
There is some discussion that FS2020 should have SimConnect functionality, but I don't have FS2020 so I can't yet confirm.

**Comment by wegylexy** [comment]
Unless you need new features, version 4 of `10.0.61637.0` works with P3D and MSFS too.
