### ISSUE TITLE
Example on how to connect to MSFS2020 and get some information as an example?

### ISSUE THREAD

**Issue by zephirus** [mharj/jsimconnect#4]
Hi,

Is it possible to have a more detailed example on how to connect to MSFS2020 and get some information?
I was looking at the NearestAirports class and I'm already stuck at the "host" and "port" part.

Do I need to have something else running in order to connect to MSFS? How to know the IP Address and port?

Sorry if this question is already explained in the documentation but I'm really confused.

Thanks.

**Comment by 1anakin20** [comment]
I can connect to MSFS2020 by setting the IP address to the computer running it, if its on the same machine then use the localhost address. Normally 127.0.0.1. For the port, I don't recall the source where I got it, but 500 works.
If you can't connect with those settings, you may need to install developers tools in MSFS2020.
You can use this library the same way with MSFS2020 as with any other version.
 Here are the docs: https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimConnect%2FSimConnect_SDK.htm. You can check here if the API feature you want is already supported.

**Comment by zephirus** [comment]
Thanks! I managed to connect with port 500. Even so, I'm still struggling to get information from the game. For example, if I want to get the coordinates of the plane, how can I do it? I can't see in the code where to start to get that information. If someone could show me how to do it, it would be awesome.

**Comment by Monroe07** [comment]
I can a little later today. I have been working on making a GPS of sorts that among other things keeps track of the nearest airports within a range as well as other aircraft. I also have a working instrument panel written in Java that uses JSimConnect. Unless someone else does it before me, I'll tell you what you need to know to get data from MS Flight Sim X/2020.

**Comment by Monroe07** [comment]
I apologize if it takes me more time than expected to make an example. In reply to the earlier talk about where the port/ip settings for connecting to simconnect come from, they are in a file called SimConnect.xml. The File is located at the following location. 
Ensure the "Show hidden folders" option is enabled in your file explorer as the appdata folder is hidden by default.
C:\Users\[Username]\AppData\Roaming\Microsoft Flight Simulator\SimConnect.xml file. If you google Simconnect.xml, there are many guides on how to set it up (and create a new one with just the info you need). in it is set the port and IP address of the network card you plan to use. I'll attach an example of the one I have.

![image](https://user-images.githubusercontent.com/20032550/116957457-bb9c3280-ac4c-11eb-9db6-b100e7198aa8.png)

**Comment by zephirus** [comment]
Hi Monroe07, really appreciate your help. And I will wait for your example as long as it takes. Thank you! Don't know if you use Discord. I leave my username if you want to contact me more directly. zephirus#3113

**Comment by 1anakin20** [comment]
In the folder [Samples](https://github.com/mharj/jsimconnect/tree/cce2a4a3ce07b14c9cc9051715ef449ac1f03be1/samples/flightsim/simconnect/samples) there are lot of demos showing how to use this library. For example this one is to get the [nearest airpots](https://github.com/mharj/jsimconnect/blob/cce2a4a3ce07b14c9cc9051715ef449ac1f03be1/samples/flightsim/simconnect/samples/NearestAirports.java).

**Comment by zephirus** [comment]
I tried that one @1anakin20 but I don't understand where I can get something from there.

**Comment by Monroe07** [comment]
Have you gotten any of the other samples to work? It will give me an indication of your skill level. Unfortunately it is not as simple as getting the right function calls down, but you also have to understand the documentation of both the JSimConnect API and the Microsoft SimConnect documentation. I can write a simpler example, but it will be futile if you don't have the fundamentals of working with SimConnect and Java.

**Comment by zephirus** [comment]
I have a little bit more than a year of experience with java. I can understand most of the code, for example the "nearest airports" code. Maybe I'm expecting that example to show something but it's not supposed to? I mean, if I run it I get a message saying I'm connected, nothing more, so that is the point where I am. What do I need to do more in this example?

**Comment by Monroe07** [comment]
Correct, the example only outputs debug statements to show that it connected. The "handleAirportList" function runs through the list of airports but does nothing with it other than create a "menu" in the flight sim (which I never implemented myself). It is up to the user to decide what to do with it (like print them in the console). For example, for each airport, it converts and stores each airports into an  Airport object after getting its lat, Lon, dist, and heading as doubles. That being said, there are better outlets for getting help with the API than opening a GitHub issue because you don't understand how the example works. There is a prerequisite understanding of how SimConnect communicates, as there is documentation on how it works from Microsoft and Prepar3d. I say that not as an attack, but as a way of saying that you should probably be sure you know what you're getting into. Best of luck!

**Comment by zephirus** [comment]
You're right. The issue was opened about the connection and if it would be possible to have a better example. it was not meant to be a request for a tutorial or something. Thanks, I will take a better look at all the documentation of SimConnect.
